### ISSUE TITLE
Arch Linux trademark policy

### ISSUE THREAD

**Issue by jonathonf** [arch-linux-gui/web#9]
Hi!

I believe your project may be operating in contravention of the [Arch Linux trademark policy](https://wiki.archlinux.org/title/DeveloperWiki:TrademarkPolicy). For example:

> In general, a Remix can have applications from the Arch Linux archives added, or default applications removed, but removing or changing any infrastructure components (e.g., shared libraries or desktop components) will result in changes too large for the resulting product to be called by a Trademark. Note that if the nature of the product's divergence from Arch Linux changes, the Remix naming and Trademark use may no longer apply. 

> If you are producing a new product which is based on Arch Linux but which has more substantial changes than those described above as a Remix, you are allowed to state (and we would encourage you to do so) that your product is "derived from Arch Linux", "based on Arch Linux", or "a derivative of Arch Linux" but you may not use the Trademarks to refer to your product.

> The Arch Linux Trademarks are designed to cover use of a mark to imply origin or endorsement by the project. When a user downloads something called Arch Linux, they should know it comes from the Arch Linux project.

> Use in combination with any other marks or logos. This include use of a Trademark in a manner that creates a "combined mark," or use that integrates other wording with the Trademark in a way that the public may think of the use as a new mark.

You also use the Arch Linux logo without adhering to the following:

> In addition to the restrictions imposed above, the Trademark declaration ( ™ ) must remain intact whenever displaying the logos. 

I would urge you to contact trademarks@archlinux.org at your earliest opportunity to discuss the options for your project.

**Comment by demonkilleralg** [comment]
Hi @jonathonf, I have contacted the Arch Linux team. Thanks for letting me know.
